### PR TITLE
Diagnostics for main function

### LINKED ISSUE #1093: Missing diagnostics for unhandled Effekts in main
Consider the following program:

```scala
type MyError { MyError() }
def main() = {
  do raise[MyError](MyError(), "foo")
}
```

`main` has type `Nothing / { Exception[MyError] }`. When running `effekt bug.effekt`, one gets the following error:

```
[error] /home/tim/Dev/effekt-lang/playground/bug1.effekt:2:1: Main cannot have effects, but includes effects: { Exception[MyError] }
def main() = {
^
```

However, currently, there are no diagnostics provided via the language server for this. This means that the editor does not display this problem and the user only notices this when trying to execute the program.

### PR DESCRIPTION
**Pull request by dvdvgt**
Resolves #1093

### CODE REVIEW

**Comment by dvdvgt** [comment]
Wrong return type:
image

Multiple main functions:
image

Unhandled effects in main:
image

**Comment by dvdvgt** [comment]
Some neg tests add the wrong return type in their main function which was not detected previously

File: effekt/shared/src/main/scala/effekt/Typer.scala [hunk 1]
```diff
@@ -79,9 +79,45 @@ object Typer extends Phase[NameResolved, Typechecked] {
       // Store the backtrackable annotations into the global DB
       // This is done regardless of errors, since
       Context.commitTypeAnnotations()
+      checkMain(input.mod)
```
Comment (dvdvgt) [inline effekt/shared/src/main/scala/effekt/Typer.scala:82]: Is this really the best place to check this?

File: effekt/jvm/src/test/scala/effekt/LSPTests.scala [hunk 2]
```diff
@@ -122,6 +122,102 @@ class LSPTests extends FunSuite {
     }
   }
```
Comment (timsueberkrueb) [inline effekt/jvm/src/test/scala/effekt/LSPTests.scala:124]: Should we have a section

```
// Diagnostics
//
//
```

here?

**Review by timsueberkrueb — APPROVED** [review]
Great, thank you :)
