### PR TITLE
Fix generic equals in js backend

### LINKED ISSUE #429: Structural equality on JavaScript backend doesn't work
The structural equality on the JavaScript backend seems to be broken.
Although reflexivity (`x == x`) holds for simple, user-defined types, it doesn't work for `Some(x) == Some(x)`.

```scala
type MyType {
  MySingleCase()
}

record EmptyRecord()

def main() = {
  println(MySingleCase() == MySingleCase())   // ~> true
  println(EmptyRecord() == EmptyRecord())     // ~> true

  println(Some(MySingleCase()) == Some(MySingleCase())) // ~> false
  println(Some(EmptyRecord()) == Some(EmptyRecord()))   // ~> false
}
```

### PR DESCRIPTION
**Pull request by marzipankaiser**
Fixes #429.

### CODE REVIEW

File: effekt/shared/src/main/scala/effekt/generator/js/Transformer.scala [hunk 1]
```diff
@@ -53,7 +53,7 @@ trait Transformer {
 
     val other = freshName("other")
     def otherGet(field: JSName): js.Expr = js.Member(js.Variable(other), field)
-    def compare(field: JSName): js.Expr = js"${get(field)} !== ${otherGet(field)}"
+    def compare(field: JSName): js.Expr = js"!${$effekt.call("equals", get(field), otherGet(field))}"
```
Comment (jiribenes) [inline effekt/shared/src/main/scala/effekt/generator/js/Transformer.scala:56]: This seems a bit low-level outside of the JS AST representation, but there's probably a reason for it, right?
Otherwise it would be something like `!${js.MethodCall(js"$effekt", js"equals", get(field), otherGet(field))}`?

**Review by jiribenes — APPROVED** [review]
LGTM, I have one small nitpick for the structure of the hot-fix, but otherwise this is mergeable and improves the current state, thanks! :shipit:

File: effekt/shared/src/main/scala/effekt/generator/js/Transformer.scala (hunk 1 above)
Comment (jiribenes) [reply effekt/shared/src/main/scala/effekt/generator/js/Transformer.scala:56]: Ah, it's Scala code! `$effekt.call` is a method in `Tree.scala`.
Nevermind, retracting.
