### PR TITLE
Labels in parser

### LINKED ISSUE #960: Labels in parser
Add a `p labelledAs name` [feel free to bikeshed] combinator function that normally behaves exactly like `p`, but when `p` fails _without consuming input_, the `name` gets used for the "Expected $name, got $badToken" message when failing.
(See https://markkarpov.com/tutorial/megaparsec.html#labeling-and-hiding-things for example usage)

Example usage:
```
functionType :=
  ... <~ `=>` ~ atomicType() labelledAs "return type" ~ maybeEffects()
```

produces the following message in a failing program:
```
def show(mod: Module => ): String
                        ^ [error] Expected return type, but got ‘)’
```

instead of what I get right now (actually after #947, currently it gets stuck on `=>`):
```
def show(mod: Module => ): String
                        ^ [error] Expected identifier, but got ‘)’
```

In general, this would allow us to override "Expected $terminal, but got ')'" with "Expected $nonterminals..., but got ')'", which seems strictly better to me...

One possible implementation is to have a mutable variable with an `Option[String]` inside the `RecursiveDescent` parser with a pending label to be used by `fail` instead of its content. The only complication is that we need to correctly reset the mutable variable whenever we consume something (and we need to interact correctly in `backtrack`).

### PR DESCRIPTION
**Pull request by jiribenes**
Resolves #960

Most messages are now of the form "Expected $A but got $B".

Now says something like: "expected block type but got `}`" instead "expected identifier but got `}`" (wrong position is #958)
Screenshot 2025-05-20 at 15 21 33

### CODE REVIEW

File: effekt/shared/src/main/scala/effekt/RecursiveDescent.scala [hunk 1]
```diff
@@ -124,6 +137,7 @@ class RecursiveDescent(positions: Positions, tokens: Seq[Token], source: Source)
   def skip(): Unit =
     previous = tokens(position)
     position += 1;
+//    currentLabel = None // TODO(jiribenes, 2025-05-20): ???
```
Comment (jiribenes) [inline effekt/shared/src/main/scala/effekt/RecursiveDescent.scala:140]: I thought that this should be set to `None` once we consume a token, but it doesn't work (I get "expected identifier got `}`" for the example problem above)

**Comment by marzipankaiser** [comment]
Turns out the original approach of this PR *does* (mostly) work, it just got hidden by #958.
So I rebased onto master, re-added the setting to None on skip, and changed the dynamic binding to a co-dynamic binding, and it seems to work:
Screenshot 2025-05-30 at 15 41 15

**Comment by marzipankaiser** [comment]
Leaving it like this for now - except will later fix up the failing neg tests (and maybe add some more)

**Comment by marzipankaiser** [comment]
Fixed up the interaction with `consume`, too, and slightly changed the parser to improve error messages.
I'd suggest to merge this once its through CI and reviewed; we can add more labels incrementally when we notice error messages that could be better.

**Comment by jiribenes** [comment]
Great work, thanks a lot for following up on my crappy WIP implementation! :)

File: effekt/shared/src/main/scala/effekt/RecursiveDescent.scala [hunk 2]
```diff
@@ -197,7 +210,7 @@ class RecursiveDescent(positions: Positions, tokens: Seq[Token], source: Source)
           semi()
           if returnPosition then Return(e)
           else ExprStmt(e, stmts())
-      }
+      }) labelled "statements"
```
Comment (jiribenes) [inline effekt/shared/src/main/scala/effekt/RecursiveDescent.scala:213]: I think it's fine to merge it like this, but maybe we should also figure out a prefix version of `labelled`, this looks a bit weird for my taste.
(That's on me, I made the combinator like this :sweat_smile:)

File: effekt/shared/src/main/scala/effekt/RecursiveDescent.scala [hunk 3]
```diff
@@ -1172,8 +1188,10 @@ class RecursiveDescent(positions: Positions, tokens: Seq[Token], source: Source)
   private def functionType(): Type = {
     // Complex function type: [T]*(Int, String)*{Exc} => Int / {Effect}
     def functionTypeComplex: Maybe[Type] = backtrack {
-      maybeTypeParams() ~ maybeValueTypes() ~ (maybeBlockTypeParams() <~ `=>`) ~ atomicType() ~ maybeEffects() match {
-        case tparams ~ vparams ~ bparams ~ t ~ effs => FunctionType(tparams, vparams, bparams, t, effs)
+      maybeTypeParams() ~ maybeValueTypes() ~ (maybeBlockTypeParams() <~ `=>`)
+    } map { case tparams ~ vparams ~ bparams =>
+      (atomicType() labelled "return type") ~ maybeEffects() match {
+        case  t ~ effs => FunctionType(tparams, vparams, bparams, t, effs)
       }
```
Comment (jiribenes) [inline effekt/shared/src/main/scala/effekt/RecursiveDescent.scala:1195]: Perfect! cuts in action ✂️

File: effekt/shared/src/main/scala/effekt/RecursiveDescent.scala (hunk 2 above)
Comment (marzipankaiser) [reply effekt/shared/src/main/scala/effekt/RecursiveDescent.scala:213]: I agree, I mostly couldn't come up with a good name for it. 😅
