### PR TITLE
Fix: Object typing for bidirectional effects

### LINKED ISSUE #152: Effectful signatures are not implemented for objects
It looks like we forgot to implement capability passing for the new object feature:

```
effect Exc(): Unit

interface MyClass {
  def get(): Int / { Exc }
}

def impl = new MyClass {
  def get() = { do Exc(); 42 }
}
```

The same mechanism does already work for bidirectional effects:

```
effect Exc(): Unit

interface MyClass {
  def get(): Int / { Exc }
}

def impl() = 
  try { o.get() } 
  with o: MyClass {
    def get() = { resume { do Exc(); 42 } }
  }
  with Exc { 0 }
```
we simply forgot to implement it for objects.

@jiribenes this is related to what we discussed before (#148).

### PR DESCRIPTION
**Pull request by dvdvgt**
This issue is to close #152.

## Description

Check #152 for details.

## Tasks

- [X] Get simple example to compile
- [X] Add block parameters to operations
- [X] Write tests and find issues with current implementation
- [ ] Discuss solution for #157 

## Changelog

- **Breaking**: Deprecate `effect ... { ... }` notation in favour of `interface ... { ... }`. `effect ...` is now only allowed for singleton interfaces.
-  Add support for block parameters for operations

### CODE REVIEW

File: effekt/shared/src/main/scala/effekt/Typer.scala [hunk 1]
```diff
@@ -4,10 +4,10 @@ package typer
 /**
  * In this file we fully qualify source types, but use symbols directly
  */
-import effekt.context.{ Annotation, Annotations, Context, ContextOps }
+import effekt.context.{Annotation, Annotations, Context, ContextOps}
 import effekt.context.assertions.*
-import effekt.source.{ AnyPattern, Def, IgnorePattern, MatchPattern, ModuleDecl, Stmt, TagPattern, Term, Tree, resolve, symbol }
-import effekt.symbols.*
+import effekt.source.{AnyPattern, Def, Effectful, IgnorePattern, MatchPattern, ModuleDecl, Stmt, TagPattern, Term, Tree, resolve, symbol}
+import effekt.symbols.{BlockType, Capture, *}
```
Comment (b-studios) [inline effekt/shared/src/main/scala/effekt/Typer.scala:10]: This was probably added by accident in IntelliJ

**Comment by b-studios** [comment]
I minimized one of the failing tests to

```
interface Compose {
    def compose[A, B] {g: A => B}: A => B at {g}
}

def handler {prog: () => Unit / Compose} =
  try { prog() } with Compose {
    def compose[F, G]() = ()
  }

def main() = handler { do compose[Int,  Int] { x => 1 }; () }
```

In fact, bidirectional handlers are not yet implemented in backends other than JS (I don't know about LLVM, TBH; @phischu ?).

**Comment by b-studios** [comment]
I think it is fine to ignore the failing test for the ML backend for now and document it as "mutual recursion not supported".
