### PR TITLE
Make panics output to stdout

### LINKED ISSUE #815: Test `prompt_duplication` fails
When running the tests locally I get:

```
==> X effekt.LLVMTests.examples/llvm/prompt-duplication.effekt (llvm)  0.72s munit.ComparisonFailException:
105:        test(s"${f.getPath} (${backendName})") {
106:          assertNoDiff(run(f), expected)
107:        }
diff assertion failed
=> Obtained
    """|[error] Process exited with non-zero exit code 1.
       |""".stripMargin
=> Diff (- obtained, + expected)
 [error] Process exited with non-zero exit code 1.
+[error] Valgrind log:
    at munit.FunSuite.assertNoDiff(FunSuite.scala:11)
    at effekt.EffektTests.runPositiveTestsIn$$anonfun$1$$anonfun$1(EffektTests.scala:106)
```

I propose to delete this test.

### PR DESCRIPTION
**Pull request by jiribenes**
Trying to fix #815

### CODE REVIEW

File: libraries/llvm/panic.c [hunk 1]
```diff
@@ -3,13 +3,17 @@
 
 #include <stdio.h>
 
+// TODO:
+// this should _morally_ be using `stderr`, but we don't tee it in tests
+// see PR #823 & issue #815 for context
+
 void hole() {
-    fprintf(stderr, "PANIC: Reached a hole in the program\n");
+    printf("PANIC: Reached a hole in the program\n");
```
Comment (jiribenes) [inline libraries/llvm/panic.c:11]: This might break other tests, but I do think it's a good idea to test for panics...

File: effekt/jvm/src/test/scala/effekt/LLVMTests.scala [hunk 2]
```diff
@@ -52,5 +53,22 @@ class LLVMTests extends EffektTests {
...
+)
+
+class LLVMNoValgrindTests extends EffektTests {
+  def backendName = "llvm"
+
+  override def valgrind = false
+  override def debug = false
+
+  override lazy val positives: List[File] = noValgrind(examplesDir)
 }
```
Comment (jiribenes) [inline effekt/jvm/src/test/scala/effekt/LLVMTests.scala:74]: I don't really like this, but I don't have any other quick solutions for this...

Comment (jiribenes) [reply effekt/jvm/src/test/scala/effekt/LLVMTests.scala:74]: We could just have a convention of `llvm/novalgrind/...` or something, but that doesn't scale too well for StdlibLLVMTests...

**Review by jiribenes — COMMENTED** [review]
I'll merge this after lunch and then run the release CI pipeline again.
We can talk about this PR tomorrow...
