### PR TITLE
Fix lsp caching issues

### LINKED ISSUE #876: Inlay hints sometimes don't reappear after file edits
Consider the following program:

```scala
def main() = println("hello world")
```

After the LSP server loads initially, the following inlay hint gets shown for the inferred `io` capture:

```scala
{io} def main() = println("hello world")
```

Now enter a blank line above the `main` function. The hint disappears.

Relevant LSP trace:

```
[Trace - 11:03:56 AM] Received request 'textDocument/inlayHint - (4)'
[Trace - 11:03:56 AM] Sending response 'textDocument/inlayHint - (4)'. Processing request took 1ms
Result: [
  {
    "position": {
      "line": 0,
      "character": 0
    },
    "label": "{io}",
    "kind": 1,
    "tooltip": {
      "kind": "markdown",
      "value": "captures: `{io}`"
    },
    "paddingLeft": false,
    "paddingRight": true,
    "data": "capture"
  }
[Trace - 11:03:57 AM] Received request 'textDocument/inlayHint - (6)'
[Trace - 11:03:57 AM] Sending response 'textDocument/inlayHint - (6)'. Processing request took 0ms
Result: null
```

### PR DESCRIPTION
**Pull request by timsueberkrueb**
Depends on #885 (mostly so we can actually express the unit test).

I split `AnnotationsDB` into three separate databases which each tracks its own map. This allows us to properly distinguish types that should be annotated by their object identity (symbols, trees) and those that should be annotated by their value identity (sources).

The new types are:

* `TreeAnnotations`: key: `source.Tree`, object identity
* `SourceAnnotations`: key: `kiama.util.Source`, value identity
* `SymbolAnnotations`: key: `symbols.Symbol`, object identity

Fixes #876.

### CODE REVIEW

File: effekt/shared/src/main/scala/effekt/context/Annotations.scala [hunk 1]
```diff
@@ -6,8 +6,28 @@ import effekt.util.messages.ErrorReporter
...
+  type Value = V
+
+  override def toString = name
+}
+
+case class TreeAnnotation[K <: source.Tree, V](name: String, description: String) extends Annotation[K, V] {
+  type Value = V
+
   override def toString = name
 }
```
Comment (jiribenes) [inline effekt/shared/src/main/scala/effekt/context/Annotations.scala:32]: Beautiful :)
