### PR TITLE
Fix LLVM byte alignment for real

### LINKED ISSUE #794: Properly fix alignment of bytes on stack
The following example still segfaults:

```scala
def foo { action: (Byte, Byte) => Unit }: Unit =
  action(42.toByte, 42.toByte)

def main() = {
  foo { (b0, b1) =>
    println(42)
    println(b0)
    println(b1)
  }
}
```

I see three solutions:

1. Undo the optimization and reserve stack space twice when pushing a frame: once for the environment and once for the header.
2. Change the definition of `%Byte` to `i64` in llvm and hope for the best. This will require greate care in extern functions acting on bytes.
3. Insert `getelementptr` instructions to ask llvm to calculate the size of a frame for us.

Unsurprisingly I am for (1).

### PR DESCRIPTION
**Pull request by marvinborner**
Closes #794.

I've also added a test but it's a bit useless since the buggy parts all get optimized away and we currently only run tests *with* optimizations.

### CODE REVIEW

File: effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala [hunk 1]
```diff
@@ -580,19 +580,22 @@ object Transformer {
   }
 
   def pushFrameOnto(stack: Operand, environment: machine.Environment, returnAddressName: String, sharer: Operand, eraser: Operand)(using ModuleContext, FunctionContext, BlockContext) = {
+    if (!environment.isEmpty) {
```
Comment (marvinborner) [inline effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala:583]: Should we create an additional function for this? (like in `popEnvironmentFrom`)

**Comment by marvinborner** [comment]
After some more thought I'm not sure how my initial change would fix all of the alignment problems.

Would my second solution in which we use *packed* structural types, also be okay (2-byte change)? In general not packing structs has all kinds of potential benefits for performance but they don't apply to us anyway, since such optimizations would segfault right now(?). Because our stack allocation is fundamentally based on knowing the *exact* allocation size, I believe this to be the only correct choice.

File: effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala [hunk 2]
```diff
@@ -428,7 +428,7 @@ object Transformer {
       case machine.Type.Prompt()     => 8 // TODO Make fat?
       case machine.Type.Stack()      => 8 // TODO Make fat?
       case machine.Type.Int()        => 8 // TODO Make fat?
-      case machine.Type.Byte()       => 8
+      case machine.Type.Byte()       => 1
```
Comment (b-studios) [inline effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala:431]: Didn't @phischu just change this from 1 to 8 to fix something else?

Comment (marvinborner) [reply effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala:431]: This was an insufficient fix as described in https://github.com/effekt-lang/effekt/pull/785#issuecomment-2607553642

**Comment by b-studios** [comment]
I'll interpret the thumbs up by @phischu as an approve and merge this :)
